<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_611395b989ebf',
  'title' => '官網後台設定',
  'fields' => array(
    array(
      'key' => 'field_611395dcc4b8a',
      'label' => '一般設定',
      'name' => '',
      'type' => 'accordion',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'show_in_rest' => 0,
      'open' => 1,
      'multi_expand' => 0,
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_6113975fc4b8b',
      'label' => 'EVERY8D 簡訊平台',
      'name' => 'every8d',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'show_in_rest' => 0,
      'layout' => 'row',
      'sub_fields' => array(
        array(
          'key' => 'field_61139786c4b8c',
          'label' => '帳號',
          'name' => 'username',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_6113979ac4b8d',
          'label' => '密碼',
          'name' => 'password',
          'type' => 'password',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
        ),
        array(
          'key' => 'field_6113a04fde3ec',
          'label' => '測試模式',
          'name' => 'test_mode',
          'type' => 'true_false',
          'instructions' => '測試模式下不會真的發送簡訊',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'rsl-be-config',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
));

endif;
