<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_61108854d43ed',
  'title' => '人氣王票選資料表',
  'fields' => array(
    array(
      'key' => 'field_611088b02bcf3',
      'label' => 'Season 2',
      'name' => '',
      'type' => 'accordion',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'show_in_rest' => 0,
      'open' => 1,
      'multi_expand' => 0,
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_61108ac531654',
      'label' => '票選資料',
      'name' => 's2_vote_table',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'show_in_rest' => 0,
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => '',
      'sub_fields' => array(
        array(
          'key' => 'field_61109c9e31655',
          'label' => '手機',
          'name' => 'phone',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_61109d0331656',
          'label' => '驗證碼',
          'name' => 'verification_code',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_6110dfb165bbf',
          'label' => '請求次數',
          'name' => 'request_count',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_611223af7ca91',
          'label' => '最後請求時間',
          'name' => 'request_datetime',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'display_format' => 'Y-m-d H:i:s',
          'return_format' => 'Y-m-d H:i:s',
          'first_day' => 1,
        ),
        array(
          'key' => 'field_61109d9d31657',
          'label' => '嘗試次數',
          'name' => 'attempt_count',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'default_value' => 0,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array(
          'key' => 'field_611223ce7ca92',
          'label' => '最後嘗試時間',
          'name' => 'attempt_datetime',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'display_format' => 'Y-m-d H:i:s',
          'return_format' => 'Y-m-d H:i:s',
          'first_day' => 1,
        ),
        array(
          'key' => 'field_61109e0531658',
          'label' => '票選選手',
          'name' => 'selection',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'show_in_rest' => 0,
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'rsl-vote-table',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
));

endif;
